### ISSUE TITLE
How do you free the sessions after 60s ?

### ISSUE THREAD

**Issue by erfnemati** [apkonline/androidonlineemulator#1]
Hi,
at first thank for your great and helpful service <3
I want to know how do you free the sessions for new users? are you cleaning up all of the app and data that users install on the same device? Or you are reseting device with a new serial number,
and the other question is, are your devices have a same model and serial numbers?

**Comment by moeenio** [comment]
They don't have serial numbers, they are using emulators on CentOS virtual machines. :)
